#program prompts the user to guess the number generated by the computer. The program keeps prompting the user until the correct number is guessed.

print "Hi!"

name = raw_input("What is your name?")
print " "
print "Hi " + name
print " "
print "Lets play a game of guess the number"
print " "
print "The computer just generated a number"


numofguesses = 0
guessbox = set()


import random
for i in range (1):
    num = random.randint(1,100)
    print num
#The print function in front of num will be removed for the user


print " "
print name + "," + " Can you guess what number it is?"
print " "
while True:
    inp = raw_input ("Please enter a number between 1 and 100:")
    
    try:
        guess = int(inp)
    
    except:
        print "Please enter a number as input"
        continue

    if guess in guessbox:
        print "This number has already being guessed"
    else:
        guessbox.add(guess)

        if guess > num:
            print "Your guess is too high"

        if guess < num:
            print "Your guess is too low"

        if guess == num:
            break

    numofguesses = numofguesses + 1


if guess == num:
    numofguesses = str(numofguesses)
    
    print "Congratulations! " + name
    print "Your guess is correct"
    print "You had " + numofguesses + " incorrect guesses!"

    
    
   